### ISSUE TITLE
i18n problems

### ISSUE THREAD

**Issue by DSLM** [Xalcon/AnalyzeIO#9]
I have some questions for the i18n file.
(https://github.com/Xalcon/AnalyzeIO/blob/master/src/main/resources/assets/analyzeio/lang/en_US.lang)

1.
```
analyzeio.lootcaps.all.energy_buffer_base=§fFallback Power buffer %s
analyzeio.lootcaps.all.energy_use_base=§fFallback Power use %s
analyzeio.lootcaps.all.energy_intake_base=§fFallback Power intake %s
```
Are those three lines useless tooltips?

2.
`analyzeio.lootcaps.all.amount=§fAll Machines %s`
`analyzeio.lootcaps.amount=§f%s %s`

Why there are not "Amount" in those two tooltips?

**Comment by Xalcon** [comment]
1.: Yes, those are leftovers from an earlier release that only had the tooltip feature. These values were redundant in some cases or just plain wrong, hence why i dont use them. I will probably remove those lines in the next release.

2.: EnderIO has 6 different capacitor type bonuses. Amount is one, that is only used in a single machine, the Farming Station (Input Stack Limit). This is NOT the amount of power a machine can store or use. THe thing is, in theory, each machine could have an amount bonus, even tho it might have no effect. Since those keys can be used with possibly every machine, i cant just plainly say "Increases Maximum Stacks", since that might be wrong if that machine doesnt store any items.

The whole capacitor bonus system is not intended to be displayed in a tooltip, heck, even the Analyzer GUI is underperforming in that regard. I'm considering a redesign of the gui for the EnderIO 1.11.2 release - but for now it should help getting the information you care about for a given capacitor.

**Comment by DSLM** [comment]
Thanks, understood.
